import type { Method } from './types'

/**
 * Lista wszystkich metod onkologii integracyjnej w naszej bazie wiedzy.
 * Każda metoda ma własny wpis i podstronę pod /onkologia-integracyjna/metody/[slug].
 * Wszystkie publikacje zweryfikowane PMID/DOI w bazach pierwotnych (PubMed, Cochrane, JCO).
 */
export const METHODS: Method[] = [
  // ============ KATEGORIA A — FARMAKOLOGICZNE UZUPEŁNIAJĄCE ============
  {
    slug: 'wlewy-dozylne-witaminy-c',
    name: 'Wlewy dożylne witaminy C (IVC)',
    shortName: 'IVC',
    category: 'A',
    categoryIndex: 1,
    grade: 'moderate',
    shortDesc: 'Wysokie dawki kwasu askorbinowego podawane dożylnie. Metaanaliza Qu 2025 wykazała median survival ratio 1,83 (GRADE: moderate).',
    mainIndications: ['leczenie wspomagające w wybranych nowotworach (badania kliniczne)', 'redukcja zmęczenia onkologicznego', 'jakość życia podczas chemioterapii'],
    regulatory: [
      { country: 'PL', status: 'off-label', note: 'Brak rejestracji jako lek onkologiczny; stosowane off-label na podstawie art. 5 ust. 1 dyr. 2001/83/WE' },
      { country: 'DE', status: 'off-label', note: 'Stosowane przez Heilpraktikerów i lekarzy CAM' },
      { country: 'USA', status: 'off-label', note: 'Stosowane w klinikach integracyjnych' },
      { country: 'CH', status: 'off-label', note: 'BAG potwierdza refundację 5 metod CAM (akupunktura, antropozofia, farmakoterapia TCM, homeopatia, fitoterapia) wykonywanych przez kwalifikowanych lekarzy — IVC nie figuruje jako odrębnie refundowana metoda. Status per świadczenie do weryfikacji w danej kasie.' },
    ],
    keySources: [
      { cite: 'Qu et al. 2025 metaanaliza', journal: 'Int J Vitam Nutr Res', pmid: '40613397', type: 'metaanaliza', finding: 'Pooled median survival ratio 1,83 (95% CI 1,40–2,40; p<0,001) — n=2722, 8 badań. GRADE: moderate' },
      { cite: 'Bodeker et al. 2024 (PACMAN 2.1)', journal: 'Redox Biology', pmid: '39369582', type: 'RCT-II', finding: 'OS 16,0 vs 8,3 mies.; PFS 6,2 vs 3,9; HR 0,46 — rak trzustki, faza II randomizowana (n=34)' },
      { cite: 'Wang et al. 2022 (VITALITY)', journal: 'Clinical Cancer Research', pmid: '35929990', type: 'RCT-III', finding: 'Brak przewagi w pierwszoliniowym leczeniu mCRC. Sygnał w podgrupie RAS-mutant wymaga potwierdzenia' },
      { cite: 'Yun et al. 2015', journal: 'Science', pmid: '26541605', type: 'mechanistyczne', finding: 'Selektywna toksyczność wobec komórek KRAS/BRAF mutant w modelach przedklinicznych' },
      { cite: 'He et al. 2025', journal: 'Cell', pmid: '40023152', type: 'mechanistyczne', finding: 'Mechanizm "vitcylation" — kowalencyjna modyfikacja lysyny w STAT1 przez witC' },
    ],
    warning: 'NIE zamiast standardowego leczenia onkologicznego. Wymaga monitorowania (G6PD, funkcja nerek).',
    evidenceSignal: 'Metaanaliza 8 RCT (n=2722) raportuje pooled median survival ratio 1,83 (Qu 2025); RCT II PACMAN 2.1 w raku trzustki: OS 16,0 vs 8,3 mies. (HR 0,46).',
    highestEvidenceType: 'A',
    clinicalStatus: 'off-label-adjunct',
    evidenceGap: 'Brak akceptacji w głównych wytycznych (ASCO/NCCN/ESMO); heterogeniczność dawek, protokołów i populacji w badaniach; brak rejestracji onkologicznej.',
    evidenceContext: 'Brak fazy III rejestracyjnej wynika z braku rejestracji IVC jako leku onkologicznego — witC nieopatentowana, brak sponsora przemysłowego dla badania kosztującego 50–500 mln USD. Istniejące RCT II i metaanaliza n=2722 należą do najsilniejszej bazy w kategorii orphan supplements.',
  },
  {
    slug: 'jemiola-iscador',
    name: 'Jemioła / Viscum album (Iscador, Helixor, Abnoba viscum)',
    shortName: 'Jemioła',
    category: 'A',
    categoryIndex: 2,
    grade: 'low',
    shortDesc: 'Preparaty z Viscum album stosowane jako leczenie wspomagające — głównie poprawa jakości życia.',
    mainIndications: ['poprawa jakości życia podczas chemioterapii', 'redukcja zmęczenia onkologicznego', 'wybrane nowotwory lite (RCT)'],
    regulatory: [
      { country: 'CH', status: 'refundowane', note: 'Refundowane od 2017 jako jedna z 5 metod CAM (antropozofia)' },
      { country: 'DE', status: 'dopuszczone', note: 'Obligatoryjnie pokrywane przez GKV w paliatywnej onkologii' },
      { country: 'AT', status: 'dopuszczone', note: 'Refundacja w ramach Begleitende Krebsbehandlungen' },
      { country: 'PL', status: 'off-label', note: 'Brak refundacji; dostępne w aptekach na receptę' },
    ],
    keySources: [
      { cite: 'Kienle & Kiene 2010', journal: 'Integr Cancer Ther', pmid: '20483874', type: 'review', finding: 'Systematic review — sygnał poprawy QoL i przeżycia w wybranych RCT' },
      { cite: 'Loef & Walach 2020', journal: 'Cochrane Database', doi: '10.1002/14651858.CD007893.pub2', type: 'metaanaliza', finding: 'Cochrane — sygnał korzyści w QoL, brak twardych dowodów dla OS' },
      { cite: 'Tröger et al. 2013', journal: 'Eur J Cancer', pmid: '23890767', type: 'RCT-III', finding: 'Rak trzustki zaawansowany — OS 4,8 vs 2,7 mies. (p<0,001), n=220 — wieloośrodkowy RCT (z 2013 r.)' },
    ],
    warning: 'Stosowanie wymaga wykwalifikowanego lekarza. NIE zamiast leczenia standardowego.',
    evidenceSignal: 'RCT III Tröger 2013 (n=220, Eur J Cancer): OS 4,8 vs 2,7 mies. p<0,001 w zaawansowanym raku trzustki. Cochrane review 2020 — sygnał korzyści w QoL.',
    highestEvidenceType: 'A',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Heterogeniczność preparatów rynkowych (Iscador, Helixor, Abnoba viscum) — różne profile lektyn; brak metaanalizy obejmującej OS pomimo istnienia RCT III.',
    evidenceContext: 'Brak dalszych RCT III wynika z heterogeniczności preparatów i braku jednego sponsora dla badania, nie z braku sygnału klinicznego. W Niemczech obligatoryjnie pokrywane przez GKV w paliatywnej onkologii.',
  },
  {
    slug: 'kurkumina',
    name: 'Kurkumina',
    shortName: 'Kurkumina',
    category: 'A',
    categoryIndex: 3,
    grade: 'low',
    shortDesc: 'Polifenol z kurkumy. Badania głównie przedkliniczne i fazy I/II.',
    mainIndications: ['leczenie wspomagające w chemioterapii (badania)', 'redukcja stanu zapalnego'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement diety; brak rejestracji jako lek onkologiczny' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement (FDA GRAS)' },
    ],
    keySources: [
      { cite: 'Howells et al. 2019', journal: 'J Nutr', pmid: '31132111', type: 'RCT-II', finding: 'Curcumin + FOLFOX w mCRC — PFS poprawione, n=27' },
      { cite: 'Kanai et al. 2011', journal: 'Cancer Chemother Pharmacol', pmid: '20859741', type: 'RCT-I', finding: 'Bezpieczeństwo w raku trzustki + gemcitabine' },
    ],
    warning: 'Niska biodostępność doustna. Interakcje z lekami CYP3A4.',
    evidenceSignal: 'RCT IIa Howells 2019 (n=27, J Nutr): kurkumina + FOLFOX w mCRC bezpieczna, sygnał PFS. Liczne badania fazy I/II w różnych nowotworach.',
    highestEvidenceType: 'B',
    clinicalStatus: 'off-label-adjunct',
    evidenceGap: 'Brak RCT III; mała próba dotychczasowych badań; problem standaryzacji preparatów (formy liposomalne/Meriva vs surowa).',
    evidenceContext: 'Kurkumina nieopatentowana — brak sponsora dla RCT III. Aktualne badania kliniczne używają form standaryzowanych o 5–20× wyższej biodostępności niż surowa.',
  },
  {
    slug: 'melatonina',
    name: 'Melatonina',
    shortName: 'Melatonina',
    category: 'A',
    categoryIndex: 4,
    grade: 'low',
    shortDesc: 'Hormon szyszynki badany jako adjuwant onkologiczny.',
    mainIndications: ['redukcja toksyczności chemioterapii', 'poprawa snu u pacjentów onkologicznych'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement (do 5 mg) i Rx (powyżej)' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement' },
      { country: 'DE', status: 'dopuszczone', note: 'Lek na receptę dla wybranych wskazań snu' },
    ],
    keySources: [
      { cite: 'Seely et al. 2012', journal: 'Integr Cancer Ther', pmid: '22019490', type: 'metaanaliza', finding: 'Adjuwant chemio — sygnał redukcji śmiertelności 1-roku i toksyczności' },
      { cite: 'Wang et al. 2012', journal: 'Cancer Chemother Pharmacol', pmid: '22271210', type: 'metaanaliza', finding: 'Solid tumors — sygnał poprawy odpowiedzi i przeżycia' },
    ],
    warning: 'Interakcje z immunosupresantami i lekami przeciwkrzepliwymi.',
    evidenceSignal: 'Meta-analiza Seely 2012 (PMID 22019490): sygnał redukcji śmiertelności 1-roku w adjuwancie chemio. Meta-analiza Wang 2012: poprawa odpowiedzi i przeżycia w solid tumors.',
    highestEvidenceType: 'A',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Heterogeniczność dawek (3–20 mg), schematów i populacji; brak nowszych RCT III; NIE figuruje w ASCO/SIO Anxiety 2023.',
    evidenceContext: 'Substancja OTC szeroko dostępna, brak komercyjnego interesu dla RCT III w onkologii. Sygnał historyczny utrzymujący się 20+ lat.',
  },
  {
    slug: 'witamina-d',
    name: 'Witamina D',
    shortName: 'Witamina D',
    category: 'A',
    categoryIndex: 5,
    grade: 'moderate',
    shortDesc: 'Suplementacja cholekalcyferolu — sygnał poprawy OS w wybranych nowotworach.',
    mainIndications: ['leczenie deficytu witD u pacjentów onkologicznych', 'wspomaganie zdrowia kości'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement i Rx; refundacja niektórych wskazań' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement' },
    ],
    keySources: [
      { cite: 'Keum et al. 2019', journal: 'Ann Oncol', pmid: '30796437', type: 'metaanaliza', finding: 'Suplementacja vit D obniża śmiertelność z powodu raka (RR 0,87)' },
      { cite: 'Manson et al. 2019 (VITAL)', journal: 'NEJM', pmid: '30415629', type: 'RCT-III', finding: 'Brak redukcji incydencji raka; sygnał w late follow-up' },
    ],
    warning: 'Hiperkalcemia przy nadmiarze. Wymaga monitorowania 25(OH)D.',
    evidenceSignal: 'Metaanaliza Keum 2019 (Ann Oncol): suplementacja vit D obniża śmiertelność z powodu raka (RR 0,87). RCT III VITAL (Manson 2019): sygnał late follow-up.',
    highestEvidenceType: 'A',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Wpływ głównie na śmiertelność (late effect), nie na incydencję; brak jednoznacznych wytycznych dawkowych dla onkologii.',
    evidenceContext: 'Witamina D nieopatentowana — RCT VITAL (Manson 2019) jest jednym z nielicznych dużych RCT III, sfinansowanym przez NIH/USA, nie przez przemysł.',
  },
  {
    slug: 'omega-3',
    name: 'Kwasy omega-3 (EPA/DHA)',
    shortName: 'Omega-3',
    category: 'A',
    categoryIndex: 6,
    grade: 'low',
    shortDesc: 'Kwasy tłuszczowe omega-3 — sygnał ograniczenia kacheksji onkologicznej.',
    mainIndications: ['kacheksja onkologiczna', 'wspomaganie tolerancji chemioterapii'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement i lek (Omacor/Lovaza Rx)' },
    ],
    keySources: [
      { cite: 'Meta-analiza RCT 2024', journal: 'meta-analiza', pmid: '38220400', type: 'metaanaliza', finding: 'Omega-3 + masa ciała w kacheksji onkologicznej — istotny wzrost masy w podgrupach RCT (WMD+0,99 kg; 95% CI)' },
    ],
    warning: 'Działanie przeciwzakrzepowe — uwzględnić przy leczeniu przeciwkrzepliwym.',
    evidenceSignal: 'Metaanaliza 2024 (PMID 38220400): omega-3 + masa ciała w kacheksji onkologicznej — istotny wzrost masy w podgrupach RCT.',
    highestEvidenceType: 'A',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Heterogeniczność preparatów EPA/DHA, dawkowania, długości terapii; brak RCT III dla większości wskazań poza kacheksją.',
    evidenceContext: 'Brak RCT III finansowanego przez przemysł farmaceutyczny — substancja nieopatentowana, bez możliwości zwrotu kosztów badania.',
  },
  {
    slug: 'glutamina',
    name: 'Glutamina',
    shortName: 'Glutamina',
    category: 'A',
    categoryIndex: 7,
    grade: 'low',
    shortDesc: 'Aminokwas. KLUCZOWE: PRZECIWWSKAZANA w HSCT (MASCC/ISOO 2020).',
    mainIndications: ['zapobieganie mucositis (selektywne wskazania)'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement; forma jelitowa w żywieniu medycznym' },
    ],
    keySources: [
      { cite: 'Elad et al. 2020 (MASCC/ISOO)', journal: 'Cancer', doi: '10.1002/cncr.33100', type: 'wytyczne', finding: 'REKOMENDACJA PRZECIWKO parenteralnej glutaminie w HSCT' },
      { cite: 'Sayles et al. 2016', journal: 'Cochrane', doi: '10.1002/14651858.CD012162', type: 'metaanaliza', finding: 'Niejednoznaczny efekt; umiarkowana korzyść w wybranych schematach' },
    ],
    warning: 'PRZECIWWSKAZANA w HSCT wg MASCC/ISOO 2020.',
    evidenceSignal: 'MASCC/ISOO 2020: rekomendacja przeciwko parenteralnej glutaminie w HSCT. Cochrane Sayles 2016: niejednoznaczny efekt, umiarkowana korzyść w wybranych schematach.',
    highestEvidenceType: 'A',
    clinicalStatus: 'not-recommended',
    evidenceGap: 'Status silnie zależny od drogi podania, populacji i wskazania — nie ma jednej ogólnej rekomendacji. Sprzeczne sygnały.',
    evidenceContext: 'Substancja OTC bez pojedynczego sponsora dla badań rejestracyjnych. MASCC/ISOO 2020 stworzyło rekomendacje na podstawie dostępnych RCT bez przemysłowego finansowania.',
  },
  {
    slug: 'n-acetylocysteina',
    name: 'N-acetylocysteina (NAC)',
    shortName: 'NAC',
    category: 'A',
    categoryIndex: 8,
    grade: 'very-low',
    shortDesc: 'Prekursor glutationu. Możliwy negatywny wpływ na efekt chemio/radioterapii.',
    mainIndications: ['leczenie zatrucia paracetamolem', 'eksperymentalnie: ochrona toksyczności chemio'],
    regulatory: [
      { country: 'PL', status: 'dopuszczone', note: 'Rejestracja jako mukolityk i odtrutka paracetamolu (NIE onko)' },
    ],
    keySources: [
      { cite: 'Sayin et al. 2014', journal: 'Sci Transl Med', pmid: '24477002', type: 'mechanistyczne', finding: 'NAC może promować progresję nowotworu w modelach przedklinicznych' },
    ],
    warning: 'KONTROWERSJA: dane przedkliniczne sugerują przyspieszenie progresji.',
    evidenceSignal: 'Sayin 2014 (Sci Transl Med, PMID 24477002): NAC może promować progresję nowotworu w modelach przedklinicznych KRAS. Dane kliniczne sporne.',
    highestEvidenceType: 'P',
    clinicalStatus: 'experimental',
    evidenceGap: 'Sprzeczne sygnały przedkliniczne: ochrona zdrowych tkanek vs możliwa promocja progresji. Brak jednoznacznych danych klinicznych.',
    evidenceContext: 'Substancja zarejestrowana jako mukolityk i odtrutka paracetamolu — nie ma rejestracji onkologicznej. Brak komercyjnego interesu dla RCT III w onkologii.',
  },

  // ============ KATEGORIA B — KONWENCJONALNE TECHNOLOGIE/PROCEDURY (NIE CAM) ============
  {
    slug: 'hipertermia-lokoregionalna',
    name: 'Hipertermia lokoregionalna (RHT)',
    shortName: 'RHT',
    category: 'B',
    categoryIndex: 1,
    grade: 'moderate',
    shortDesc: 'Lokoregionalna hipertermia — NIE "pseudomedycyna whole-body". RCT dla mięsaków.',
    mainIndications: ['mięsaki tkanek miękkich', 'rak szyjki macicy (z radioterapią)', 'nowotwory pęcherza', 'wybrane mCRC'],
    regulatory: [
      { country: 'DE', status: 'refundowane', note: 'GKV pokrywa wybrane wskazania (DEGRO guidelines)' },
      { country: 'NL', status: 'refundowane', note: 'Refundowane w wybranych ośrodkach' },
      { country: 'CH', status: 'refundowane', note: 'Refundacja dla wskazań ESMO/DEGRO' },
      { country: 'PL', status: 'off-label', note: 'Brak refundacji NFZ; ośrodki prywatne' },
    ],
    keySources: [
      { cite: 'Issels et al. 2018', journal: 'JAMA Oncol', pmid: '29450452', type: 'RCT-III', finding: 'Mięsaki — DFS 67% vs 50% przy 10 latach z hipertermią' },
      { cite: 'van der Zee et al. 2000', journal: 'Lancet', pmid: '10841125', type: 'RCT-III', finding: 'Rak szyjki — CR 83% vs 57%; OS 51% vs 27% przy 3 latach' },
    ],
    warning: 'NIE myllić z hipertermią ogólnoustrojową (WBH) krytykowaną przez NRL pkt 11.',
    evidenceSignal: 'RCT III Issels 2018 (EORTC/ESHO, mięsaki): DFS 67% vs 50% przy 10-letnim follow-up (p=0,017); OS 62% vs 47% (p=0,042). RCT III van der Zee 2000 rak szyjki: CR 83% vs 57%.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Ograniczona dostępność technologii (drogi sprzęt); brak pełnej refundacji w PL.',
    evidenceContext: 'NIE jest typowo CAM — to konwencjonalna technologia medyczna z wytycznymi DEGRO/ESMO. Brak finansowania publicznego w PL jest barierą administracyjną, nie merytoryczną.',
  },
  {
    slug: 'tlenoterapia-hiperbaryczna',
    name: 'Tlenoterapia hiperbaryczna (HBOT)',
    shortName: 'HBOT',
    category: 'B',
    categoryIndex: 2,
    grade: 'high',
    shortDesc: 'Tlen pod podwyższonym ciśnieniem. UHMS — 14 wskazań. REFUNDOWANE przez NFZ.',
    mainIndications: ['popromienna nekroza tkanek miękkich i kości', 'martwica popromienna pęcherza', 'rany niegojące się onko'],
    regulatory: [
      { country: 'PL', status: 'refundowane', note: 'NFZ refunduje 14 wskazań UHMS' },
      { country: 'USA', status: 'dopuszczone', note: 'Medicare/Medicaid pokrywają wskazania UHMS' },
      { country: 'DE', status: 'refundowane', note: 'GKV dla wybranych wskazań' },
    ],
    keySources: [
      { cite: 'Bennett et al. 2016 (Cochrane)', journal: 'Cochrane', doi: '10.1002/14651858.CD005005.pub4', type: 'metaanaliza', finding: 'HBOT redukuje ryzyko osteoradionecrosis' },
      { cite: 'UHMS 14 Indications', journal: 'UHMS Guidelines', type: 'wytyczne', finding: '14 zatwierdzonych wskazań klinicznych' },
    ],
    warning: 'NIE myllić z "tlenoterapią dożylną" (NRL pkt 7) — inna metoda fizyczna.',
    evidenceSignal: 'Cochrane Bennett 2016: HBOT redukuje ryzyko osteoradionecrosis i wspomaga gojenie ran popromiennych. UHMS wymienia 14 wskazań klinicznych.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Ograniczona dostępność technologii (komory hiperbaryczne); refundacja NFZ tylko dla wybranych wskazań UHMS.',
    evidenceContext: 'NIE jest CAM — konwencjonalna procedura z 14 wskazaniami UHMS. NFZ refunduje wybrane wskazania, w tym popromienne uszkodzenia. NIE myllić z „tlenoterapią dożylną" (lista NRL pkt 7).',
  },
  {
    slug: 'terapia-fotodynamiczna',
    name: 'Terapia fotodynamiczna (PDT)',
    shortName: 'PDT',
    category: 'B',
    categoryIndex: 3,
    grade: 'high',
    shortDesc: 'Aktywacja światłem fotosensybilizatora (porfimer sodowy). FDA-approved 6 wskazań.',
    mainIndications: ['rak przełyku', 'NDRP (wczesny endobronchialny)', 'rak podstawnokomórkowy skóry', 'keratoza słoneczna', 'przełyk Barretta z dysplazją', 'chłoniak skórno-T-komórkowy'],
    regulatory: [
      { country: 'USA', status: 'dopuszczone', note: 'FDA approved (Photofrin) dla 6 wskazań onkologicznych' },
      { country: 'EU', status: 'dopuszczone', note: 'EMA approved; częściowa refundacja' },
      { country: 'PL', status: 'refundowane', note: 'NFZ refunduje dla wybranych wskazań onkologicznych' },
    ],
    keySources: [
      { cite: 'Agostinis et al. 2011', journal: 'CA Cancer J Clin', pmid: '21617154', type: 'review', finding: 'Comprehensive review PDT — mechanizm, wskazania, dowody' },
      { cite: 'Overholt et al. 2007', journal: 'Gastrointest Endosc', pmid: '17643434', type: 'RCT-III', finding: 'PDT w przełyku Barretta — redukcja progresji do raka' },
    ],
    warning: 'Fotouczulenie skóry do 6 tygodni. NIE myllić z "naświetlaniem laserowym krwi" (NRL pkt 8).',
    evidenceSignal: 'PDT (porfimer sodowy) zatwierdzony przez FDA dla 6 wskazań onkologicznych. RCT III Overholt 2007 Barrett.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Ograniczona dostępność technologii; specyficzne wskazania.',
    evidenceContext: 'NIE jest CAM — FDA-approved konwencjonalna procedura onkologiczna od dekad. EMA approved. Refundacja w PL przez NFZ dla wybranych wskazań.',
  },
  {
    slug: 'ttfields-optune',
    name: 'TTFields (Optune) — pola przemienne',
    shortName: 'TTFields',
    category: 'B',
    categoryIndex: 4,
    grade: 'high',
    shortDesc: 'Tumor Treating Fields (Optune). FDA approved GBM (2011/2015), mezothelioma (2019), mNSCLC (2024). EU CE mark.',
    mainIndications: ['glejak wielopostaciowy (GBM)', 'złośliwy międzybłoniak opłucnej', 'przerzutowy NDRP (Optune Lua 2024)'],
    regulatory: [
      { country: 'USA', status: 'dopuszczone', note: 'FDA approved 2011/2015/2019/2024' },
      { country: 'EU', status: 'dopuszczone', note: 'CE mark (NIE EMA — urządzenie medyczne)' },
      { country: 'DE', status: 'refundowane', note: 'GKV refunduje dla GBM' },
      { country: 'PL', status: 'eksperymentalne', note: 'Brak refundacji NFZ; dostępne komercyjnie' },
    ],
    keySources: [
      { cite: 'Stupp et al. 2017 (EF-14)', journal: 'JAMA', pmid: '29260225', type: 'RCT-III', finding: 'GBM newly diagnosed — OS 20,9 vs 16,0 mies. (HR 0,63; p<0,001), n=695' },
      { cite: 'Ceresoli et al. 2019 (STELLAR)', journal: 'Lancet Oncol', pmid: '31628016', type: 'RCT-II', finding: 'Mezothelioma — OS 18,2 mies. z TTFields + chemio' },
    ],
    warning: 'NIE to samo co "leczenie laptopem" (Chmielowiec 21.01.2025) — TTFields to FDA-approved.',
    evidenceSignal: 'RCT III Stupp 2017 EF-14 (JAMA, n=695): GBM newly diagnosed — OS 20,9 vs 16,0 mies. (HR 0,63; p<0,001). RCT II STELLAR Ceresoli 2019 mezothelioma: OS 18,2 mies.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Brak refundacji NFZ w PL (dostępne komercyjnie). Wymóg noszenia urządzenia ≥18h/dobę.',
    evidenceContext: 'NIE jest CAM — FDA approved 2011/2015/2019/2024, EU CE mark. Brak refundacji w PL jest barierą finansową, nie merytoryczną.',
  },

  // ============ KATEGORIA C — MEDYCYNA STYLU ŻYCIA (GUIDELINE-SUPPORTED) ============
  {
    slug: 'aktywnosc-fizyczna-w-onkologii',
    name: 'Aktywność fizyczna w onkologii',
    shortName: 'Aktywność fizyczna',
    category: 'C',
    categoryIndex: 1,
    grade: 'high',
    shortDesc: 'Wytyczne ASCO/SIO 2024 (Bower JE), ACSM 2019. Redukcja zmęczenia, poprawa OS.',
    mainIndications: ['zmęczenie onkologiczne (rekomendacja 1)', 'poprawa jakości życia', 'redukcja nawrotu raka piersi/jelita', 'tolerancja chemioterapii'],
    regulatory: [
      { country: 'PL', status: 'dopuszczone', note: 'Programy rehabilitacji onkologicznej NFZ' },
      { country: 'USA', status: 'dopuszczone', note: 'ASCO/SIO guideline 2024' },
      { country: 'EU', status: 'dopuszczone', note: 'ESMO guidelines' },
    ],
    keySources: [
      { cite: 'Bower et al. 2024 (ASCO/SIO)', journal: 'JCO', pmid: '38754041', type: 'wytyczne', finding: 'Aktywność fizyczna — REKOMENDACJA 1 dla cancer-related fatigue' },
      { cite: 'Campbell et al. 2019 (ACSM)', journal: 'Med Sci Sports Exerc', pmid: '31626055', type: 'wytyczne', finding: 'Roundtable on Exercise — guideline dla pacjentów onkologicznych' },
      { cite: 'McTiernan et al. 2019', journal: 'Med Sci Sports Exerc', pmid: '31626056', type: 'metaanaliza', finding: 'Aktywność fizyczna obniża ryzyko nawrotu raka piersi/jelita' },
      { cite: 'Metaanaliza 2026', journal: 'systematic review meta-analysis', pmid: '41894932', type: 'metaanaliza', finding: 'Aktywność fizyczna obniża śmiertelność całkowitą u pacjentów onkologicznych — 13 RCT, n=3282, HR 0,74 (moderate certainty)' },
    ],
    warning: 'Indywidualizacja programu — konsultacja w przypadku przerzutów kostnych, anemii.',
    evidenceSignal: 'Metaanaliza 2026 (PMID 41894932, 13 RCT n=3282): obniżenie śmiertelności całkowitej HR 0,74 (moderate certainty). ASCO-SIO 2024 Bower: REKOMENDACJA 1 dla cancer-related fatigue.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Indywidualizacja programu wymaga konsultacji (przerzuty kostne, anemia, kardiotoksyczność chemio).',
    evidenceContext: 'Najmocniejsza baza dowodowa wśród wszystkich metod supportive care. Wytyczne ASCO/SIO, ACSM, ESMO.',
  },
  {
    slug: 'dieta-srodziemnomorska',
    name: 'Dieta śródziemnomorska',
    shortName: 'Dieta śródziemnomorska',
    category: 'C',
    categoryIndex: 2,
    grade: 'moderate',
    shortDesc: 'Dieta — prewencja PIERWOTNA raka piersi (PREDIMED 2015), redukcja śmiertelności CVD.',
    mainIndications: ['prewencja pierwotna raka piersi (PREDIMED)', 'redukcja śmiertelności sercowo-naczyniowej'],
    regulatory: [
      { country: 'PL', status: 'dopuszczone', note: 'Rekomendacje IŻŻ' },
      { country: 'EU', status: 'dopuszczone', note: 'EFSA, ESMO recognizes' },
    ],
    keySources: [
      { cite: 'Toledo et al. 2015 (PREDIMED)', journal: 'JAMA Intern Med', pmid: '26365989', type: 'RCT-III', finding: 'Prewencja PIERWOTNA raka piersi — HR 0,32 dla diety + EVOO, n=4282' },
      { cite: 'Estruch et al. 2018', journal: 'NEJM', pmid: '29897866', type: 'RCT-III', finding: 'PREDIMED reanaliza — redukcja zdarzeń sercowo-naczyniowych' },
    ],
    warning: 'NIE "dieta cudowna" w leczeniu. Korzyść głównie prewencyjna pierwotna i kardiologiczna.',
    evidenceSignal: 'RCT III PREDIMED/Toledo 2015 (PMID 26365989, n=4282): prewencja PIERWOTNA raka piersi — HR 0,32 dla diety + EVOO vs kontrola.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Główna korzyść w prewencji pierwotnej i kardiologii, nie w aktywnej terapii onkologicznej; brak refundacji programu dietetycznego w PL.',
    evidenceContext: 'Hiszpańskie RCT publiczne (PREDIMED) — najsilniejsza baza dla prewencji pierwotnej raka piersi.',
  },
  {
    slug: 'akupunktura-w-onkologii',
    name: 'Akupunktura w onkologii',
    shortName: 'Akupunktura',
    category: 'C',
    categoryIndex: 3,
    grade: 'moderate',
    shortDesc: 'ASCO/SIO 2022 (Mao JJ) — rekomendacja dla bólu onkologicznego, AIMSS, CINV.',
    mainIndications: ['ból onkologiczny (rekomendacja ASCO/SIO 2022)', 'AIMSS', 'CINV', 'uderzenia gorąca'],
    regulatory: [
      { country: 'DE', status: 'refundowane', note: 'GKV refunduje akupunkturę dla chronic back/knee pain' },
      { country: 'CH', status: 'refundowane', note: 'Refundacja jako 1 z 5 metod CAM (od 2017)' },
      { country: 'USA', status: 'dopuszczone', note: 'ASCO/SIO 2022 guideline; Medicare dla wybranych wskazań' },
      { country: 'UK', status: 'dopuszczone', note: 'NICE NG193, NG144' },
      { country: 'PL', status: 'off-label', note: 'Brak refundacji; dostępne komercyjnie' },
    ],
    keySources: [
      { cite: 'Mao et al. 2022 (ASCO/SIO)', journal: 'JCO', pmid: '36122322', type: 'wytyczne', finding: 'Akupunktura — rekomendacja dla bólu onkologicznego' },
      { cite: 'Hershman et al. 2018', journal: 'JAMA', pmid: '29998338', type: 'RCT-III', finding: 'AIMSS — redukcja bólu stawów po IA (SWOG S1200)' },
    ],
    warning: 'Wymaga wykwalifikowanego akupunkturzysty. NIE substytut leczenia.',
    evidenceSignal: 'ASCO/SIO 2022 Mao (PMID 36122322): rekomendacja dla bólu onkologicznego i AIMSS. RCT III Hershman 2018 SWOG S1200: AIMSS, redukcja bólu stawów po IA.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Brak refundacji NFZ w PL; jakość zabiegu zależy od kwalifikacji akupunkturzysty.',
    evidenceContext: 'Refundowana w DE (chronic back/knee), CH (5 metod CAM), UK (NICE NG193). W PL barierą jest brak refundacji.',
  },
  {
    slug: 'mbsr-mbcr',
    name: 'MBSR / MBCR — uważność w onkologii',
    shortName: 'MBSR/MBCR',
    category: 'C',
    categoryIndex: 4,
    grade: 'moderate',
    shortDesc: 'Mindfulness-Based Stress Reduction / Cancer Recovery. ASCO/SIO 2023 (Carlson LE).',
    mainIndications: ['lęk i depresja u pacjentów onkologicznych (rekomendacja ASCO/SIO 2023)', 'redukcja zmęczenia', 'poprawa QoL'],
    regulatory: [
      { country: 'PL', status: 'dopuszczone', note: 'Stosowane w ramach psychoonkologii' },
      { country: 'USA', status: 'dopuszczone', note: 'ASCO/SIO 2023 guideline' },
    ],
    keySources: [
      { cite: 'Carlson et al. 2013 (MBCR)', journal: 'JCO', pmid: '23918953', type: 'RCT-II', finding: 'MBCR vs SET — redukcja stresu i poprawa QoL u kobiet z rakiem piersi' },
      { cite: 'Carlson et al. 2023 (ASCO/SIO)', journal: 'JCO', pmid: '37582238', type: 'wytyczne', finding: 'MBSR/MBCR — rekomendacja dla anxiety/depression' },
    ],
    warning: 'Wymaga wykwalifikowanego instruktora. Korzyść głównie psychospołeczna.',
    evidenceSignal: 'ASCO/SIO 2023 Carlson (PMID 37582238): rekomendacja dla anxiety/depression. RCT II Carlson 2013 MBCR: redukcja stresu i poprawa QoL u kobiet z rakiem piersi.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Wymaga wykwalifikowanego instruktora; korzyść głównie psychospołeczna.',
    evidenceContext: 'Wytyczne ASCO/SIO 2023. Dostępne w PL w ramach psychoonkologii (brak refundacji programu).',
  },

  // ============ KATEGORIA D — MODULACJA IMMUNOLOGICZNA I EKSPERYMENTALNE ============
  {
    slug: 'lentinan-psk',
    name: 'Lentinan / PSK — grzyby lecznicze',
    shortName: 'Lentinan/PSK',
    category: 'D',
    categoryIndex: 1,
    grade: 'low',
    shortDesc: 'Polisacharydy z grzybów (shiitake, coriolus). PSK refundowany w Japonii dla raka żołądka.',
    mainIndications: ['adjuwant chemio raka żołądka (Japonia)', 'paliatywne wsparcie immunologiczne'],
    regulatory: [
      { country: 'JP', status: 'refundowane', note: 'PSK/Krestin — refundowany dla raka żołądka (od 1985)' },
      { country: 'PL', status: 'OTC', note: 'Suplement diety; brak rejestracji onko' },
    ],
    keySources: [
      { cite: 'Oba et al. 2007', journal: 'Cancer Immunol Immunother', pmid: '17106715', type: 'metaanaliza', finding: 'PSK adjuwant raka żołądka — sygnał poprawy OS (Japonia)' },
    ],
    warning: 'Dowody głównie z Japonii. Suplementy w PL nie są tożsame z farmaceutycznym PSK.',
    evidenceSignal: 'Metaanaliza Oba 2007 (PMID 17106715): PSK adjuwant chemio raka żołądka — sygnał poprawy OS (Japonia). Refundacja PSK/Krestin w Japonii od 1985.',
    highestEvidenceType: 'A',
    clinicalStatus: 'guideline-supported',
    evidenceGap: 'Dowody głównie z populacji japońskiej; ograniczone dla rasy kaukaskiej; brak rejestracji onkologicznej w UE/USA.',
    evidenceContext: 'PSK refundowany w Japonii od 1985 — przykład że substancja naturalna może mieć status rejestracyjny przy odpowiednim sponsorze publicznym.',
  },
  {
    slug: 'artesunat-off-label',
    name: 'Artesunat off-label w onkologii',
    shortName: 'Artesunat',
    category: 'D',
    categoryIndex: 2,
    grade: 'very-low',
    shortDesc: 'Lek przeciwmalaryczny. Off-label w onkologii MOŻLIWY na podstawie art. 5 dyr. 2001/83/WE.',
    mainIndications: ['eksperymentalne off-label w onkologii (badania I/II)'],
    regulatory: [
      { country: 'PL', status: 'dopuszczone', note: 'Zarejestrowany dla malarii; off-label onko możliwy' },
      { country: 'EU', status: 'dopuszczone', note: 'EMA approved; off-label onko na zasadach art. 5' },
      { country: 'USA', status: 'dopuszczone', note: 'FDA approved dla ciężkiej malarii (2020)' },
    ],
    keySources: [
      { cite: 'Krishna et al. 2014', journal: 'EBioMedicine', pmid: '26137537', type: 'RCT-I', finding: 'Faza I — bezpieczeństwo artesunatu w mCRC' },
      { cite: 'Efferth 2017', journal: 'Semin Cancer Biol', pmid: '28254675', type: 'review', finding: 'Mechanizm + dane przedkliniczne i wczesne kliniczne' },
    ],
    warning: 'BRAK badań III fazy. Off-label NIE oznacza rutynowego użycia onkologicznego.',
    evidenceSignal: 'RCT I Krishna 2014 (EBioMedicine): bezpieczeństwo artesunatu w mCRC. Review Efferth 2017: mechanizm + dane przedkliniczne i wczesne kliniczne.',
    highestEvidenceType: 'C',
    clinicalStatus: 'experimental',
    evidenceGap: 'Brak RCT III w onkologii; off-label możliwy na podstawie art. 5 dyr. 2001/83/WE; wymaga oceny gospodarki żelazem.',
    evidenceContext: 'Lek przeciwmalaryczny zarejestrowany dla ludzi — barierą RCT III w onkologii jest brak wskazania rejestracyjnego, nie brak mechanizmu (potwierdzony fazą I/II).',
  },
  {
    slug: 'niskie-dawki-naltrexonu',
    name: 'Niskie dawki naltreksonu (LDN)',
    shortName: 'LDN',
    category: 'D',
    categoryIndex: 3,
    grade: 'very-low',
    shortDesc: 'Hipoteza mechanistyczna / off-label. Brak solidnych danych klinicznych w onkologii.',
    mainIndications: ['badania eksperymentalne (brak rekomendacji klinicznej)'],
    regulatory: [
      { country: 'PL', status: 'rejestracja-jako-inne-wskazanie', note: 'Naltrekson zarejestrowany jako leczenie uzależnień' },
      { country: 'USA', status: 'off-label', note: 'Recepta off-label — wybrane kliniki' },
    ],
    keySources: [
      { cite: 'Brown & Panksepp 2009', journal: 'Med Hypotheses', pmid: '19041189', type: 'review', finding: 'Hipoteza mechanizmu — TLR-4, oś opioidowa' },
    ],
    warning: 'BARDZO niska baza dowodowa w onkologii. Stosowanie eksperymentalne.',
    evidenceSignal: 'Brown & Panksepp 2009 (PMID 19041189): hipoteza mechanizmu — TLR-4, oś opioidowa. Brak RCT klinicznych w onkologii.',
    highestEvidenceType: 'P',
    clinicalStatus: 'experimental',
    evidenceGap: 'Brak RCT klinicznych w onkologii; bardzo niska baza dowodowa kliniczna.',
    evidenceContext: 'Naltrekson zarejestrowany dla leczenia uzależnień, off-label onkologia bardzo eksperymentalna. Brak komercyjnego interesu dla RCT III (lek generyczny od dekad).',
  },
  {
    slug: 'salinomycyna',
    name: 'Salinomycyna — paradoks NRL',
    shortName: 'Salinomycyna',
    category: 'D',
    categoryIndex: 4,
    grade: 'very-low',
    shortDesc: 'Antybiotyk jonoforowy aktywny in vitro wobec CSC. KLUCZOWE: NIE zarejestrowany dla ludzi. Figuruje na liście NRL Nr 2/21/VIII jako "bez podstaw" — pomimo realnych dowodów przedklinicznych.',
    mainIndications: ['NIE leczenie standardowe ani off-label rutynowy', 'wyłącznie ścieżka badania klinicznego (URPL + Komisja Bioetyczna)', 'wskazania badane: rak jajnika, piersi, jelita grubego, prostaty, trzustki, żołądka, glejak (in vitro, xenograft, pilotażowe kliniczne)'],
    regulatory: [
      { country: 'PL', status: 'eksperymentalne', note: 'Brak rejestracji jako produkt leczniczy dla ludzi. Możliwe ścieżki stosowania klinicznego: badanie kliniczne (URPL + Komisja Bioetyczna), compassionate use (art. 83 rozp. 726/2004), named patient program, indywidualne sprowadzenie z zagranicy (art. 4 ust. 7–9 Prawa farmaceutycznego).' },
      { country: 'EU', status: 'eksperymentalne', note: 'Brak rejestracji EMA dla ludzi. Możliwa compassionate use (art. 83 rozp. 726/2004)' },
      { country: 'USA', status: 'eksperymentalne', note: 'Brak rejestracji FDA dla ludzi. Tylko IND lub badania kliniczne' },
    ],
    keySources: [
      { cite: 'Naujokat & Steinhart 2012', journal: 'BioMed Res Int', pmid: '23251084', type: 'review', finding: 'Salinomycyna jako lek targetujący nowotworowe komórki macierzyste (CSC)' },
      { cite: 'Gupta et al. 2009 (Weinberg MIT)', journal: 'Cell', pmid: '19682730', type: 'mechanistyczne', finding: 'Salinomycyna 100-krotnie skuteczniejsza od paklitakselu w eliminowaniu CSC raka piersi (in vitro)' },
      { cite: 'Antoszczak & Huczynski 2015 (UAM Poznan)', journal: 'Bioorg Med Chem Lett', pmid: '25553435', type: 'mechanistyczne', finding: 'Pochodne salinomycyny — synteza i aktywność przeciwnowotworowa (polski wkład)' },
    ],
    warning: 'Brak rejestracji jako produkt leczniczy dla ludzi (EMA/FDA/URPL). Stosowanie kliniczne odbywa się na różnych podstawach prawnych: badanie kliniczne, compassionate use (art. 83 rozp. 726/2004), named patient program, indywidualne sprowadzenie z zagranicy (art. 4 ust. 7–9 Prawa farmaceutycznego). Decyzja należy do kwalifikowanego klinicysty i pacjenta po pełnej świadomej zgodzie. Konieczne monitorowanie toksyczności systemowej (neurologicznej, kardiologicznej). Substancja figuruje na liście NRL Nr 2/21/VIII jako „bez podstaw" — paradoks wobec realnych dowodów przedklinicznych.',
    evidenceSignal: 'Gupta 2009 Cell (Weinberg/MIT, PMID 19682730): 100× silniejsza niż paklitaksel wobec CSC raka piersi (in vitro). Naujokat 2012 (PMID 23251084): review jako target CSC.',
    highestEvidenceType: 'P',
    clinicalStatus: 'experimental',
    evidenceGap: 'Brak rejestracji dla ludzi (substancja weterynaryjna). Brak RCT klinicznych II/III. Wymaga ścieżki badania klinicznego z URPL i Komisją Bioetyczną lub indywidualnego sprowadzenia.',
    evidenceContext: 'Brak RCT III wynika z braku rejestracji dla ludzi — substancja weterynaryjna i nieopatentowana. Istniejące dane przedkliniczne są silne; barierą jest ścieżka regulacyjna, nie sygnał skuteczności.',
  },
  {
    slug: 'boswellia-serrata',
    name: 'Boswellia serrata (kadzidłowiec indyjski)',
    shortName: 'Boswellia',
    category: 'D',
    categoryIndex: 5,
    grade: 'low',
    shortDesc: 'Inhibitor 5-LOX i NF-κB; AKBA przenika barierę krew-mózg. Najsilniejszy sygnał kliniczny: redukcja obrzęku mózgu po radioterapii (RCT Kirste 2011) — GRADE moderate dla tego wskazania; GRADE low dla pozostałych.',
    mainIndications: ['obrzęk mózgu po radioterapii (najsilniejsze dowody)', 'stany zapalne w onkologii', 'wsparcie przy GBM i przerzutach mózgowych'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement diety; preparaty Sallaki, Boswellin dostępne w aptekach' },
      { country: 'DE', status: 'dopuszczone', note: 'Heilpraktiker; H15 (Steigerwald) stosowany klinicznie; bez refundacji GKV' },
      { country: 'CH', status: 'refundowane', note: 'W zakresie fitoterapii (1 z 5 refundowanych metod CAM)' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement; trial NCT03149081 (phase I, MUSC)' },
    ],
    keySources: [
      { cite: 'Kirste et al. 2011', journal: 'Cancer', doi: '10.1002/cncr.26101', type: 'RCT-II', finding: 'RCT double-blind n=44: 60% pacjentów ≥75% redukcja obrzęku mózgu vs 26% placebo (p=0,023); BS 4200 mg/d podczas RT' },
      { cite: 'Dejonckheere et al. 2025', journal: 'Adv Radiat Oncol', doi: 'PMC11904484', type: 'review', finding: 'Meta-narrative systematic review: kliniczne potwierdzenie BA przy obrzęku mózgu po RT; redukcja zależności od deksametazonu' },
      { cite: 'Morikawa et al. 2024', journal: 'Front Pharmacol', pmid: '38194131', type: 'RCT-I', finding: 'Faza Ia window-of-opportunity (rak piersi): BS hamuje proliferację nowotworową' },
    ],
    warning: 'Koagulopatie, DVT, zaburzenia krzepnięcia — przeciwwskazane. Ostrożność: ciąża, laktacja, przeszczepy. Jakość preparatu krytyczna: BSE-018 (30% AKBA) lub H15 > zwykłe proszki ziołowe.',
    evidenceSignal: 'RCT II double-blind Kirste 2011 (n=44): 60% pacjentów ≥75% redukcja obrzęku mózgu po RT vs 26% placebo (p=0,023). Systematic review Dejonckheere 2025.',
    highestEvidenceType: 'B',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Brak RCT III; ograniczona próba (n=44 w RCT pilotowym); GRADE moderate tylko dla obrzęku po RT, low dla pozostałych wskazań.',
    evidenceContext: 'Brak RCT III bo Boswellia to preparat ziołowy nieopatentowany. Mimo to istnieje RCT II double-blind z istotnym statystycznie wynikiem klinicznym dla obrzęku mózgu po RT.',
    experimental: true,
  },
  {
    slug: 'cordyceps',
    name: 'Cordyceps (sinensis / militaris CS-4)',
    shortName: 'Cordyceps',
    category: 'D',
    categoryIndex: 6,
    grade: 'low',
    shortDesc: 'Polisacharydy i cordycepina — aktywacja NK, Th1, M1; adaptogenne wsparcie HHM-ATP. Najsilniejszy sygnał kliniczny w raku płuca jako adjuwant chemio/RT.',
    mainIndications: ['adjuwant chemio/RT w raku płuca (najlepiej udokumentowane)', 'zmęczenie onkologiczne (CRF)', 'immunostymulacja podczas leczenia mielotoksycznego'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement diety; CS-4 (hodowla C. militaris) dostępna w aptekach' },
      { country: 'DE', status: 'dopuszczone', note: 'Heilpraktiker; bez refundacji GKV' },
      { country: 'CH', status: 'refundowane', note: 'Potencjalnie w ramach fitoterapii/TCM' },
      { country: 'JP', status: 'OTC', note: 'Tradycja TCM (Dongchongxiacao); brak rejestracji onko' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement; CS-4 standaryzowany komercyjnie' },
    ],
    keySources: [
      { cite: 'Liu et al. 2024 metaanaliza', journal: 'J Ethnopharmacology', doi: '10.1016/j.jep.2024.118434', type: 'metaanaliza', finding: '12 RCT n=928, rak płuca + chemio/RT: ↑ response rate, ↑ QoL, ↑ immunofunkcja, ↓ radiopneumopatia i ADRs. Optymalne: 6 g/d, 21 dni/3-4 cykle' },
      { cite: 'Wang et al. 2025', journal: 'PMC', doi: 'PMC12302630', type: 'RCT', finding: 'Skuteczność CS w pierwotnym raku wątroby — wspomaganie anti-fatigue' },
      { cite: 'Pleiotropic review 2026', journal: 'Frontiers', doi: 'PMC13029327', type: 'review', finding: 'C. militaris CS-4 jako alternatywa dla dzikiego C. sinensis; profil adaptogenny i immunomodulacyjny' },
    ],
    warning: 'Transplantacja narządów — ostrożność (aktywacja NK = potencjalne ryzyko odrzucenia). Choroby autoimmunologiczne. Jakość: dziki C. sinensis (Himalaje) ≠ hodowlany CS-4 — CS-4 bardziej spójny i tańszy, problem zafałszowań rynkowych. Brak danych w ciąży.',
    evidenceSignal: 'Metaanaliza Liu 2024 (12 RCT, n=928, J Ethnopharmacology): rak płuca + chemio/RT — ↑ response rate, ↑ QoL, ↓ radiopneumopatia.',
    highestEvidenceType: 'A',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Dane głównie azjatyckie, heterogeniczne; brak RCT III europejskich/amerykańskich; jakość preparatu (dziki vs hodowlany CS-4) różna.',
    evidenceContext: 'Tradycja TCM ponad 1300 lat. Dane głównie z Chin — brak komercyjnego interesu dla RCT III w UE/USA (substancja nieopatentowana).',
    experimental: true,
  },
  {
    slug: 'reishi-ganoderma',
    name: 'Reishi / Ganoderma lucidum (Lingzhi)',
    shortName: 'Reishi',
    category: 'D',
    categoryIndex: 7,
    grade: 'low',
    shortDesc: 'Beta-glukany (GLP) — Th1, M1, NK; triterpeny (kwasy ganodermowe) — NF-κB↓. Cochrane 2016 (Jin): 5 RCT n=373, RR 1,50 odpowiedzi na chemio + chemio jako adjuwant.',
    mainIndications: ['adjuwant immunostymulacyjny w skojarzeniu z chemio/RT', 'poprawa QoL podczas leczenia onkologicznego', 'wsparcie funkcji immunologicznej (CD3/CD4/CD8)'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement diety; dostępne w aptekach (Reishi Aktiv, MycoMedica, ShroomMe)' },
      { country: 'DE', status: 'dopuszczone', note: 'Heilpraktiker; TCM Heilpflanzen; bez refundacji GKV' },
      { country: 'CH', status: 'refundowane', note: 'W ramach refundowanego TCM/fitoterapii' },
      { country: 'JP', status: 'OTC', note: 'Tradycja Lingzhi/Reishi; bez rejestracji onko (vs PSK/Krestin)' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement; FDA nie zatwierdziło dla leczenia raka' },
    ],
    keySources: [
      { cite: 'Jin et al. 2016 (Cochrane)', journal: 'Cochrane Database Syst Rev', pmid: '27045603', type: 'metaanaliza', finding: '5 RCT n=373: G. lucidum + chemio/RT — RR 1,50 odpowiedzi na leczenie (95% CI 0,90-2,51); poprawa CD3, CD4, CD8 i QoL; bez przeżycia długoterminowego' },
      { cite: 'Santesso & Wieland 2016', journal: 'Eur J Integr Med', pmid: '28083078', type: 'review', finding: 'Podsumowanie Cochrane: sygnał korzyści immunologicznej' },
      { cite: 'Medicinal mushrooms 2026', journal: 'Front Cancer Control Soc', doi: '10.3389/fcacs.2026.1774081', type: 'review', finding: 'G. lucidum obiecujące w supportive care; PSK i lentinan najsilniej przebadane' },
    ],
    warning: 'BEZWZGLĘDNA OSTROŻNOŚĆ przy przeszczepach (aktywacja NK/T może spowodować odrzucenie). Interakcje z warfaryną (case reports trombocytopenii). Hepatotoksyczność: rzadka przy proszku z całych grzybów. Ostrzeżenie przy ER+/PR+ raku piersi (estrogen-like in vitro przy niektórych frakcjach). Jakość: ekstrakt wodny/etanolowy > proszek surowy.',
    evidenceSignal: 'Cochrane Jin 2016 (PMID 27045603, 5 RCT n=373): G. lucidum + chemio/RT — RR 1,50 odpowiedzi na leczenie; poprawa CD3/CD4/CD8 i QoL.',
    highestEvidenceType: 'A',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Mała próba w RCT; populacja głównie chińska; brak pewnych danych o przeżyciu długoterminowym.',
    evidenceContext: 'Tradycja Lingzhi 2000+ lat. Cochrane review z 2016. Brak RCT III bo substancja naturalna nieopatentowana.',
    experimental: true,
  },
  {
    slug: 'maitake-d-fraction',
    name: 'Maitake D-fraction (Grifola frondosa)',
    shortName: 'Maitake',
    category: 'D',
    categoryIndex: 8,
    grade: 'low',
    shortDesc: 'Beta-1,6/1,3-glukan wiążący Dectin-1 na makrofagach, DC i NK; ADCC; redukcja MDSC. MD-fraction ma dodatkowy sygnał pro-apoptotyczny.',
    mainIndications: ['immunostymulacja podczas mielotoksycznej chemio', 'wsparcie aktywności NK', 'badania fazy I/II w raku piersi'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement diety; dostępne w aptekach i sklepach z suplementami' },
      { country: 'JP', status: 'OTC', note: 'G. frondosa nie refundowana (vs PSK/Krestin z T. versicolor)' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement; faza badań klinicznych (NIH NCI)' },
      { country: 'DE', status: 'dopuszczone', note: 'Heilpraktiker; jak Reishi — potencjalnie w TCM/fitoterapii' },
    ],
    keySources: [
      { cite: 'Kodama et al. 2003', journal: 'J Med Food', pmid: '14977447', type: 'RCT-I', finding: 'n=10 (różne raki bez chemio): D-fraction ↑ NK activity u wszystkich; ↓ markery nowotworowe; hamowanie progresji — pilotaż bez grupy kontrolnej' },
      { cite: 'Deng et al. 2009', journal: 'Cancer Immunology', doi: 'PMC3751581', type: 'RCT-II', finding: 'Faza I/II breast cancer n=34 (Grifola polysaccharide): efekty immunostymulujące i immunoinhibicyjne jednocześnie (CD3+ ↑, CD25+ ↓)' },
      { cite: 'Synergy with vitamin C 2009', journal: 'PMC', doi: 'PMC2840554', type: 'mechanistyczne', finding: 'Wzajemne potęgowanie efektu immunostymulacyjnego (in vitro/in vivo)' },
    ],
    warning: 'Analogicznie jak Reishi: ostrożność przy transplantacji i autoimmunologii. Standaryzacja KLUCZOWA: D-fraction ≠ surowy proszek z maitake — preparaty Nanba/Yukiguni Maitake mają deklarowany poziom D-fraction. Potencjalne działanie hipoglikemiczne (ostrożność przy cukrzycy + chemio). Brak danych w ciąży.',
    evidenceSignal: 'Pilotaż Kodama 2003 (PMID 14977447, n=10): D-fraction ↑ NK activity u wszystkich pacjentów. Faza I/II Deng 2009 rak piersi n=34: immunostymulacja.',
    highestEvidenceType: 'C',
    clinicalStatus: 'experimental',
    evidenceGap: 'Brak RCT III; mała próba; standaryzacja D-fraction ≠ surowy proszek; brak formalnych wytycznych.',
    evidenceContext: 'PSK refundowany w Japonii, ale D-fraction maitake — nie. Brak komercyjnego sponsora dla RCT III.',
    experimental: true,
  },
  {
    slug: 'wilcacora',
    name: 'Wilcacora / Uncaria tomentosa (Koci Pazur)',
    shortName: 'Wilcacora',
    category: 'D',
    categoryIndex: 9,
    grade: 'low',
    shortDesc: 'POA (Pentacyclic Oxindole Alkaloids) — DC, makrofagi, NF-κB; TOA antagonistyczne wobec POA. Tylko preparaty POA-standaryzowane mają działanie immunostymulacyjne.',
    mainIndications: ['redukcja neutropenii po chemio (jedyne RCT)', 'immunostymulacja podczas leczenia', 'odbudowa parametrów immunologicznych po cyklach chemio'],
    regulatory: [
      { country: 'PL', status: 'OTC', note: 'Suplement diety; Vilcacora, Koci Pazur (Nefdespa, Primaforce, Swanson)' },
      { country: 'DE', status: 'dopuszczone', note: 'Heilpraktiker; bez refundacji GKV' },
      { country: 'CH', status: 'refundowane', note: 'Fitoterapia — potencjalnie refundowana indywidualnie' },
      { country: 'AT', status: 'dopuszczone', note: 'ÖÄK Diplom w fitoterapii' },
      { country: 'USA', status: 'OTC', note: 'Dietary supplement; brak FDA approval dla onko' },
    ],
    keySources: [
      { cite: 'Farias et al. 2012', journal: 'Evid Based Complement Alternat Med', pmid: '22811748', type: 'RCT-II', finding: 'RCT n~50, IDC stage II + chemio FAC: U. tomentosa 300 mg/d → znamienna redukcja neutropenii (p<0,05), odbudowa DNA damage, poprawa immunologii; bez wzrostu toksyczności' },
      { cite: 'EMA HMPC 2015', journal: 'EMA Assessment Report Uncaria tomentosa', doi: 'EMA/HMPC/Uncaria-tomentosa-2015', type: 'wytyczne', finding: 'Tradycyjne zastosowanie immunostymulacyjne POA; przeciwstawny efekt frakcji POA vs TOA — wymóg standaryzacji POA-only dla preparatów farmakologicznie aktywnych' },
      { cite: 'EMA HMPC 2015', journal: 'EMA Assessment Report', type: 'wytyczne', finding: 'Brak well-established medical use; tradycyjne zastosowanie w immunostymulacji (TU)' },
    ],
    warning: 'ABSOLUTNE PRZECIWWSKAZANIE: transplantacja narządów (immunostymulacja POA → ryzyko odrzucenia). Leki immunosupresyjne (takrolimus, cyklosporyna): antagonizm farmakodynamiczny. CIĄŻA: contraindicated — tradycyjnie stosowana jako środek poronny u Asháninka. ER+/PR+ raki: ostrożność (estrogenne alkaloidy w danych zwierzęcych). KRYTYCZNE: tylko preparaty POA-only — POA+TOA się znoszą.',
    evidenceSignal: 'RCT II Farias 2012 (PMID 22811748, n~50, IDC + FAC): redukcja neutropenii po chemio (p<0,05), naprawa DNA damage, poprawa immunologii.',
    highestEvidenceType: 'B',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Jedyne RCT kliniczne; brak RCT III; EMA HMPC 2015 klasyfikuje jako traditional use; krytyczne: tylko preparaty POA-only.',
    evidenceContext: 'Tradycja Asháninka 2000+ lat (Peru). Brak RCT III bo substancja ziołowa nieopatentowana. ClinicalTrials NCT02045719 aktywne w Brazylii.',
    experimental: true,
  },
  {
    slug: 'inhalacje-wodorowe-h2',
    name: 'Inhalacje wodorowe (H₂ Gas Inhalation)',
    shortName: 'H₂ inhalacja',
    category: 'D',
    categoryIndex: 10,
    grade: 'low',
    shortDesc: 'Cząsteczkowy wodór (H₂) selektywnie neutralizuje toksyczne ROS (•OH, ONOO⁻) zachowując ROS sygnalizacyjne. Najsilniejszy sygnał kliniczny: redukcja toksyczności RT (2 RCT 2024-2025).',
    mainIndications: ['redukcja toksyczności radioterapii (zapalenie jelit, mucositis, ototoksyczność)', 'zmęczenie onkologiczne podczas chemio/immunoterapii', 'ochrona narządów (nerki, wątroba, serce) podczas chemio'],
    regulatory: [
      { country: 'JP', status: 'dopuszczone', note: 'Advanced Medical Care B (Klasa 2B) od XII 2016 — MHLW zatwierdziła; jRCTs031180352. Najwyższy status regulacyjny na świecie' },
      { country: 'PL', status: 'OTC', note: 'Urządzenia wyrobami medycznymi klasy I/IIa (CE); brak rejestracji H₂ jako leku; brak refundacji NFZ' },
      { country: 'DE', status: 'dopuszczone', note: 'Heilpraktikerzy; bez refundacji GKV; status suplementu/wyrobu' },
      { country: 'USA', status: 'eksperymentalne', note: 'FDA: urządzenia bez approval jako lek; aktywne badania NCT03818347, NCT04175301, NCT05728112' },
      { country: 'EU', status: 'OTC', note: 'Brak rejestracji EMA; wyroby medyczne z CE' },
    ],
    keySources: [
      { cite: 'Liu et al. 2025', journal: 'Adv Radiat Oncol', pmid: '41020280', type: 'RCT-II', finding: 'RCT n=58, rak szyjki macicy + CCRT: H₂ (66%/33%, 3L/min, 2h/d) → ↓ CRP, NLR, IL-6, FOB; łagodniejsze zapalenie jelit; brak interferencji z efektem antynowotworowym (RECIST bez różnicy)' },
      { cite: 'Chitapanarux et al. 2024', journal: 'Onco Targets Ther', pmid: '39493677', type: 'RCT-I', finding: 'Pilot RCT n=10, LAHNC + CCRT: 100% compliance, 330 sesji bez NZD, 10% grade-3 leukopenii (vs ~77% historycznie), mucositis 30-40% (vs >60%); 8/10 bez choroby po 11 mies.' },
      { cite: 'Zufayri Mohd Noor et al. 2023', journal: 'Asian Pac J Cancer Prev', pmid: '36708550', type: 'review', finding: 'Systematic review 27 badań: H₂ poprawia przeżywalność, QoL, parametry krwi jako terapia niezależna lub adjuwant; potrzeba dalszych RCT' },
      { cite: 'Chen et al. 2020', journal: 'Med Gas Res', pmid: '32541132', type: 'kohortowe', finding: 'n=58 NSCLC, H₂ inhalacja 4-5h/d × 5 mies.: ↓ objawy płucne; H₂ + immunoterapia/chemo > H₂ alone > kontrola w PFS' },
    ],
    warning: 'WAŻNE: H₂ neutralizuje SELEKTYWNIE •OH i ONOO⁻ — RECIST w RCT nie wykazał interferencji z RT/chemio. Jednak: ostrożność z fazami pro-ROS w protokołach integracyjnych (artesunat IV, witC IV wysokie dawki — NIE łączyć w tym samym dniu jeśli celem jest indukcja ferroptozy). POChP/ciężka obturacja: ostrożność z kaniulą. Stężenia >4% H₂ łatwopalne — urządzenia medyczne <3%. Ciąża: brak danych. Jakość urządzenia krytyczna: CE jako wyrób medyczny, nie "wellness".',
    evidenceSignal: 'RCT II Liu 2025 (PMID 41020280, n=58, rak szyjki + CCRT): ↓ CRP, NLR, IL-6; łagodniejsze zapalenie jelit, brak interferencji RT (RECIST bez różnicy). Pilot RCT Chitapanarux 2024 LAHNC.',
    highestEvidenceType: 'B',
    clinicalStatus: 'supportive-care',
    evidenceGap: 'Brak RCT III; status urządzeń medycznych różni się między krajami; jakość urządzeń (CE klasa I/IIa vs „wellness").',
    evidenceContext: 'Japonia Advanced Medical Care B (2016) — najwyższy status regulacyjny na świecie. Aktywne badania kliniczne. Brak RCT III bo gaz molekularny nieopatentowalny.',
    experimental: true,
  },
]

/** Grupy metod według kategorii — dla list i sidebar */
export const METHODS_BY_CATEGORY = {
  A: METHODS.filter((m) => m.category === 'A').sort((a, b) => a.categoryIndex - b.categoryIndex),
  B: METHODS.filter((m) => m.category === 'B').sort((a, b) => a.categoryIndex - b.categoryIndex),
  C: METHODS.filter((m) => m.category === 'C').sort((a, b) => a.categoryIndex - b.categoryIndex),
  D: METHODS.filter((m) => m.category === 'D').sort((a, b) => a.categoryIndex - b.categoryIndex),
}

/** Znajdź metodę po slug */
export function getMethodBySlug(slug: string): Method | undefined {
  return METHODS.find((m) => m.slug === slug)
}

/** Wszystkie sluggi — do generateStaticParams */
export function getAllMethodSlugs(): string[] {
  return METHODS.map((m) => m.slug)
}
