// Pełna treść apelu obywatelskiego ws. projektu UD207 (pkt I–VI).
// Używana do: (1) wyświetlenia pełnego dokumentu na stronie, (2) przycisku „Kopiuj pełną treść”.

export const PETITION_TITLE =
  'Apel obywatelski ws. projektu ustawy UD207 (druk sejmowy nr 2598, tzw. „lex szarlatan”)'

export interface PetitionSection {
  heading: string
  paragraphs: string[]
}

export const PETITION_SECTIONS: PetitionSection[] = [
  {
    heading: 'I. Przedmiot pisma',
    paragraphs: [
      'Składam niniejsze pismo (apel obywatelski) jako obywatelka/obywatel Rzeczypospolitej Polskiej w sprawie projektu ustawy o zmianie ustawy o prawach pacjenta i Rzeczniku Praw Pacjenta (UD207, druk sejmowy nr 2598). Po pierwszym czytaniu projekt został skierowany do podkomisji; na posiedzeniu 17 czerwca 2026 r. (zapis wideo z posiedzenia dostępny w archiwum transmisji Sejmu) podkomisja zawęziła zakaz „metod niebędących świadczeniem zdrowotnym” do czterech grup pacjentów — osób małoletnich, chorych onkologicznie, ciężko i nieuleczalnie chorych oraz osób z zaburzeniami psychicznymi — i dodała przesłankę „zagrożenia dla zdrowia lub życia”. Projekt wraca do Komisji Zdrowia, sprawa jest więc realnie otwarta.',
      'My, pacjentki i pacjenci, nie zgadzamy się, by w demokratycznym państwie prawa jeden urzędnik — Rzecznik Praw Pacjenta, powoływany przez Prezesa Rady Ministrów, niebędący ani sądem, ani ciałem przedstawicielskim — jednostronnie i bez merytorycznej kontroli sądu kształtował rynek świadczeń zdrowotnych w Polsce i decydował, które metody leczenia są dla nas dostępne. Popieramy ściganie oszustów. Sprzeciwiamy się temu, by walka z oszustwem stała się pretekstem do odebrania pacjentom prawa wyboru i skupienia władzy nad medycyną w rękach jednego organu.',
      'Wnosimy o oparcie regulacji na następujących zasadach:',
      '1. Prawo pacjenta do wyboru terapii. O sposobie leczenia — w tym o legalnych terapiach wspomagających — decyduje świadomy pacjent wspólnie z lekarzem, a nie urząd.',
      '2. Dostęp do legalnych terapii wspomagających. Państwo nie powinno blankietowo eliminować legalnych metod wspomagających, z których pacjenci dziś korzystają — w tym dostępnych legalnymi drogami: badania klinicznego oraz eksperymentu leczniczego za świadomą zgodą pacjenta (to jedyna legalna ścieżka dla substancji nieposiadających rejestracji dla ludzi), stosowania leków poza wskazaniami rejestracyjnymi i indywidualnego importu docelowego. Dla pacjentów onkologicznych, dla których liczy się każdy dzień, ścieżki te powinny być szybkie i wolne od zbędnych formalności, a świadczenia finansowane przez samych pacjentów nie obciążają środków publicznych.',
      '3. Mądra regulacja zamiast zakazu — na wzór Europy. Paramedycynę należy uregulować przez kwalifikacje i rejestr (model Heilpraktiker w Niemczech, dyplomy ÖÄK w Austrii, rozwiązania szwajcarskie), a nie przez penalizację całej dziedziny. Dotyczy to także legalnie wykonywanych zawodów i usług wspomagających — fizjoterapeutów, dietetyków, masażystów, zielarzy, akupunkturzystów i innych — którzy nie roszczą sobie prawa do „leczenia”, lecz wspierają pacjentów i odciążają system ochrony zdrowia; nieostre kryteria i efekt mrożący nie mogą ich stygmatyzować ani wypychać z rynku.',
      '4. Wolność debaty i wypowiedzi. Ustawa powinna ścigać czyn — oszustwo w złej wierze — a nie wypowiedź lekarza, naukowca czy pacjenta o leczeniu (art. 54 i art. 73 Konstytucji RP).',
      '5. Dezinformacja w osobnym trybie, nie pod natychmiastową karą. Spory o metody powinny być rozstrzygane w jawnym rejestrze z prawem do odpowiedzi i korekty — symetrycznie, w obie strony — a nie natychmiast wykonalną sankcją (art. 54 i art. 73 Konstytucji RP).',
      '6. Jawna procedura ekspercka. Zanim padnie kara, niezależna ocena z gradacją dowodów (GRADE/HTA/ESMO-MCBS) i ujawnianiem konfliktów interesów; Rzecznik nie może jednoosobowo orzekać o „aktualnej wiedzy medycznej” bez transparentnej procedury, jak ma to UOKiK.',
      '7. Żaden urząd ponad sądem. Decyzje Rzecznika Praw Pacjenta muszą podlegać realnej, merytorycznej kontroli niezależnego sądu powszechnego — analogicznie do kontroli decyzji UOKiK przez Sąd Ochrony Konkurencji i Konsumentów — a nie wyłącznie ocenie ich legalności przez sąd administracyjny. Rygor natychmiastowej wykonalności powinien być dopuszczalny tylko wyjątkowo, z mocnym uzasadnieniem i szybką ścieżką odwoławczą.',
      '8. Domniemanie niewinności. Nieprawomocne decyzje nie mogą być publikowane ani wykonywane jak prawomocne wyroki, zanim potwierdzi je sąd (art. 42 ust. 3 Konstytucji RP).',
      '9. Nikt nie zostaje bez opieki. Wykluczenie świadczeniodawcy nie może oznaczać pozostawienia jego pacjentów bez ciągłości leczenia — decyzja powinna wskazywać podmiot przejmujący opiekę.',
      'Klauzula bezpieczeństwa. W razie uchwalenia ustawy bez uwzględnienia powyższych zasad wnosimy o odmowę podpisania ustawy przez Prezydenta RP (art. 122 ust. 5 Konstytucji RP) lub o skierowanie jej do Trybunału Konstytucyjnego (art. 122 ust. 3 Konstytucji RP). Szczegółowe uzasadnienie konstytucyjne oraz proponowane brzmienie przepisów zawiera Memorandum prawne dostępne na pacjentmaprawo.pl.',
    ],
  },
  {
    heading: 'II. Uzasadnienie konstytucyjne',
    paragraphs: [
      '1. Brak jawnej, niezależnej procedury eksperckiej z gradacją dowodów (art. 2 i art. 31 ust. 3 Konstytucji RP). Projekt powierza Rzecznikowi Praw Pacjenta — organowi kierowanemu przez prawnika — jednoosobowe orzekanie i nakładanie kar do 1 000 000 zł w oparciu o „zgodność z aktualną wiedzą medyczną”, kryterium sporne nawet wśród specjalistów, bez ustawowej, transparentnej procedury oceny merytorycznej z gradacją siły dowodów (np. GRADE, OCEBM, ESMO-MCBS), ujawnianiem konfliktów interesów i prawem strony do przedstawienia kontrdowodu. Dla porównania, Urząd Ochrony Konkurencji i Konsumentów, działając zbliżonymi narzędziami administracyjnymi, opiera się na jawnych wytycznych metodologicznych; projekt UD207 nie przewiduje dla Rzecznika żadnego analogicznego standardu. Powstaje ryzyko arbitralności rozstrzygnięć niespełniające standardu rzetelnej procedury i proporcjonalności.',
      '2. Naruszenie zasady określoności prawa (art. 2 Konstytucji RP, lex certa). Projekt wiąże odpowiedzialność ze zgodnością świadczenia z „aktualną wiedzą medyczną” bez precyzyjnego zdefiniowania tego pojęcia, na które w praktyce składa się wiele niepokrywających się baz i wytycznych. Sąd Najwyższy (postanowienie z 5 czerwca 2019 r., III KK 212/18) wskazał, że ocena zgodności postępowania lekarza z „aktualną wiedzą medyczną” wymaga każdorazowo dowodu z opinii biegłych, a wątpliwości należy rozstrzygać in dubio pro reo (art. 5 § 2 k.p.k.). Dodana po podkomisji przesłanka „zagrożenia dla zdrowia lub życia” jest równie niedookreślona.',
      '3. Niemożliwość wyznaczenia granicy zakazu. Te same świadczenia wspomagające bywają dla jednej osoby elementem profilaktyki, a dla innej — wspomaganiem w chorobie, o której może ona jeszcze nie wiedzieć. Adresat normy nie jest w stanie z góry ustalić, czy jego działanie jest dozwolone, a o kwalifikacji rozstrzygałby następczo i uznaniowo ten sam organ, który nakłada karę. To pogłębia wadę określoności i rzetelnej procedury.',
      '4. Naruszenie zasady proporcjonalności (art. 31 ust. 3 Konstytucji RP) — dwie strukturalne luki. Luka pierwsza — ciągłość opieki w NFZ: budżet NFZ w 2025 r. przekroczył 220 mld zł, ale Polska wydaje na ochronę zdrowia 8,1% PKB wobec średniej OECD 9,2%. System publiczny od lat nie zapewnia pełnej ciągłości opieki; część pacjentów korzysta ze świadczeń poza NFZ właśnie z powodu tej niewydolności. Projekt zaostrza penalizację świadczeniodawców, nie usuwając pierwotnej przyczyny zjawiska — środek nie jest „niezbędny” w rozumieniu art. 31 ust. 3, skoro istnieje środek mniej dotkliwy. Luka druga — deficyt reprezentatywności: w aktach projektu i Ocenie Skutków Regulacji nie wskazano publicznej konsultacji ani ankiety wśród pacjentów lub ich reprezentatywnych organizacji obejmujących pełne spektrum chorób objętych regulacją. Ponadto środek jest nie tylko zbyt szeroki, lecz i zbyt wąski: nieuczciwy podmiot może zarejestrować działalność poza Unią Europejską i pozostać poza zasięgiem ustawy, podczas gdy realnie obciążeni zostaną krajowi, uczciwi świadczeniodawcy. Wypchnięcie pacjentów, którzy dziś finansują wspomaganie z własnych środków, z powrotem do przeciążonego NFZ grozi dodatkowym, dotkliwym obciążeniem systemu, który ustawa ma rzekomo chronić.',
      '5. Równość i targetowanie najbardziej bezbronnych (art. 32 w zw. z art. 31 ust. 3 i art. 54 Konstytucji RP). Po poprawce podkomisji najostrzejszy reżim skupia się na czterech grupach o najwyższej stawce i najmniejszych siłach obrony: małoletnich, pacjentach onkologicznych, ciężko i nieuleczalnie chorych oraz osobach z zaburzeniami psychicznymi. Skutkiem jest nie ochrona najsłabszych, lecz skierowanie wobec nich najbardziej dotkliwych sankcji. Przykładowo świadczenie ujęte w wytycznych towarzystw onkologii wspomagającej (ASCO/SIO), udzielane za świadomą zgodą pacjenta i za wiedzą onkologa — jak akupunktura w nudnościach po chemioterapii — mogłoby podpaść pod reżim ustawy wyłącznie z uwagi na onkologiczną diagnozę pacjenta. Autonomię pacjenta w tym zakresie wspierają art. 47 Konstytucji RP, Konwencja z Oviedo oraz orzecznictwo ETPC (Jehovah’s Witnesses of Moscow przeciwko Rosji, skarga 302/02, 10 czerwca 2010 r.).',
      '6. Naruszenie autonomii pacjenta bez różnicowania metod (art. 47 Konstytucji RP + Konwencja z Oviedo). Konwencja z Oviedo (Rada Europy, 1997) gwarantuje pacjentowi prawo do świadomego wyboru świadczeń zdrowotnych. UD207 ogranicza tę autonomię w obszarze świadczeń uzupełniających, nie różnicując między metodami zweryfikowanymi w badaniach klinicznych a praktykami niezweryfikowanymi — operuje jedną blankietową etykietą zamiast gradacji.',
      '7. Podwójny standard dowodów. Ta sama miara medycyny opartej na dowodach, zastosowana uczciwie, obejmuje także część leczenia konwencjonalnego. W analizie onkologicznych dopuszczeń Europejskiej Agencji Leków z lat 2009–2013 około 57% wskazań weszło na rynek na podstawie punktów surogatowych, bez dowodu wydłużenia życia (Davis i wsp., BMJ 2017; PMID 28978555); spośród leków dopuszczonych przez FDA w trybie przyspieszonym jedynie 43% wykazało korzyść kliniczną po ponad pięciu latach (JAMA 2024; PMID 38583175). Wniosek jest epistemiczny, nie polemiczny: „brak mocnych badań” nie zawsze znaczy „nieskuteczne” — często znaczy „brak środków na badania taniej, niepatentowalnej substancji”. Prawo musi więc stosować gradację dowodów, a nie zero-jedynkową etykietę. Nie twierdzimy, że świadczenia wspomagające są równoważne lekom, ani że leki onkologiczne „nie działają”.',
      '8. Ryzyko nierównowagi proceduralnej w zakresie ciężaru dowodu (art. 7 i art. 77 k.p.a.). Konstrukcja, w której to świadczeniodawca ma wykazać zgodność świadczenia z nieostrym pojęciem „aktualnej wiedzy medycznej”, rodzi poważne ryzyko przerzucenia na stronę ciężaru, który w postępowaniu administracyjnym powinien spoczywać na organie.',
      '9. Penalizacja na podstawie pojęcia niedookreślonego (art. 42 Konstytucji RP). Zasada nullum crimen sine lege certa wymaga precyzyjnego określenia znamion. Pojęcie „aktualnej wiedzy medycznej” jako element znamion przewinienia administracyjnego o charakterze represyjnym nie spełnia tego standardu.',
      '10. Symetria „dezinformacji” a wolność wypowiedzi i badań (art. 54 i art. 73 Konstytucji RP). Jeśli „kwestionowanie uznanych metod” ma być traktowane jako dezinformacja, to tym samym jest nieuzasadnione odsądzanie świadczeń o udokumentowanym działaniu. Jednokierunkowy przepis grozi efektem mrożącym wobec debaty naukowej i powinien zostać zastąpiony osobnym, niesankcyjnym trybem (rejestr z prawem do odpowiedzi i korekty).',
    ],
  },
  {
    heading: 'III. Strukturalne wady postępowań ws. odpowiedzialności zawodowej',
    paragraphs: [
      'W praktyce orzeczniczej Sądu Najwyższego pojawiły się już przypadki uchylania prawomocnych orzeczeń samorządu lekarskiego ws. odpowiedzialności zawodowej z powodu rażących naruszeń proceduralnych, obejmujących: naruszenie prawa do obrony (art. 6 EKPC, art. 45 Konstytucji RP), przedawnienie czynu w postępowaniu zawodowym oraz brak wymaganej opinii biegłych przy ocenie zgodności postępowania lekarza z pojęciem niedookreślonym, jakim jest „aktualna wiedza medyczna”. Uchylenia te nastąpiły z przyczyn proceduralnych, nie merytorycznych.',
      'Wykazuje to, że już w obecnym stanie prawnym mechanizmy represji wobec lekarzy stosujących świadczenia uzupełniające produkują orzeczenia, które nie wytrzymują testu kasacyjnego. Projekt UD207 — wzmacniający uprawnienia Rzecznika Praw Pacjenta do publikacji nieprawomocnych decyzji oraz nakładania kar administracyjnych do 1 000 000 zł — rozszerza ten mechanizm, nie usuwając jego wad strukturalnych.',
    ],
  },
  {
    heading: 'IV. Kumulacja represji w obecnym stanie prawnym',
    paragraphs: [
      'W aktualnym porządku prawnym funkcjonują już mechanizmy kontroli świadczeniodawców działające równolegle w czterech torach: postępowanie zawodowe w samorządzie lekarskim (rzecznicy odpowiedzialności zawodowej, sądy lekarskie, kasacja w Sądzie Najwyższym — Izba Odpowiedzialności Zawodowej); postępowanie administracyjne przed Rzecznikiem Praw Pacjenta (kary administracyjne, decyzje rygorystyczne, kontrola sądowoadministracyjna w WSA i NSA); postępowanie karne (art. 160, art. 162 k.k. w przypadku narażenia pacjenta na niebezpieczeństwo; art. 58 ustawy o zawodach lekarza i lekarza dentysty); postępowanie cywilne (odpowiedzialność deliktowa, naruszenie praw pacjenta).',
      'Uzupełnienie ich uprawnieniami z UD207 (kary do 1 000 000 zł, publikacja nieprawomocnych decyzji, rozszerzone uprawnienia RPP) ma charakter kumulacji represji, a nie wypełnienia luki regulacyjnej. W teście Engela (ETPC, Engel przeciwko Holandii) oraz w doktrynie ne bis in idem (ETPC, Menci przeciwko Włochom) konstrukcja taka prowadzi do ryzyka naruszenia art. 4 Protokołu nr 7 do EKPC. Trybunał Konstytucyjny w wyroku P 124/15 wskazał, że nakładanie sankcji administracyjnych równolegle z sankcjami karnymi za ten sam czyn wymaga restryktywnej oceny pod kątem proporcjonalności.',
    ],
  },
  {
    heading: 'V. Na tle Europy — UD207 wbrew tendencji regulacyjnej',
    paragraphs: [
      'Żaden ze sprawdzonych systemów ochrony zdrowia w Europie nie stosuje jednej blankietowej definicji „pseudomedycyny”. Wszystkie stosują modele gradacyjne — rozróżniają metodę, wskazanie, kwalifikacje osoby wykonującej, status dowodowy i ryzyko dla pacjenta:',
      'Wielka Brytania — selektywny model NICE: metody są filtrowane według siły dowodów (np. akupunktura w przewlekłym bólu pierwotnym, wytyczne NG193), a część świadczeń bywa wycofywana po negatywnej ocenie. To filtrowanie oparte na dowodach, nie blankietowy zakaz.',
      'Niemcy — model mieszany: wybrane metody uzupełniające są refundowane w określonych wskazaniach i pod warunkiem kwalifikacji (m.in. akupunktura w przewlekłym bólu od 2007 r.), inne pozostają poza refundacją; decyduje wskazanie i jakość dowodów, nie etykieta. Równolegle funkcjonuje uregulowany zawód Heilpraktiker.',
      'Austria — czternaście dyplomów Izby Lekarskiej (ÖÄK) w obszarze metod komplementarnych, w tym uzupełniającego leczenia wspomagającego w onkologii, wykonywanego przez lekarzy z dodatkowymi kwalifikacjami (§ 11a Ärztegesetz).',
      'Szwajcaria — art. 118a Konstytucji Federalnej; wybrane metody objęte ubezpieczeniem powszechnym od 2017 r. w ramach kwalifikacji i oceny.',
      'Włochy (Toskania) — Legge regionale 9/2007: włączenie wybranych metod do publicznego systemu w ramach regionalnych wykazów świadczeń i kwalifikacji.',
      'WHO — rezolucja WHA78(14) z 27 maja 2025 r. (przyjęta z udziałem Polski jako państwa UE) przyjmująca Strategię WHO ds. Medycyny Tradycyjnej, Komplementarnej i Integracyjnej 2025–2034. Oświadczenie UE z 24 maja 2025 r. wskazało na potrzebę integracji opartej na bezpieczeństwie, jakości, skuteczności i evidence-based medicine, z zastrzeżeniem przeciwdziałania praktykom „harmful and/or ineffective”.',
      'Wspólną cechą tych modeli jest gradacja, nie blankietowa etykieta. Komparatystyka nie dowodzi, że każda metoda jest skuteczna — dowodzi, że nowoczesne systemy zdrowia różnicują metodę, wskazanie, kwalifikacje, dowody i ryzyko. UD207, operując jedną definicją niezależnie od tych rozróżnień, odchyla się od tego standardu i ryzykuje niezgodność z zasadą określoności prawa (art. 2) oraz proporcjonalności (art. 31 ust. 3 Konstytucji RP).',
    ],
  },
  {
    heading: 'VI. Stanowisko końcowe — mądra regulacja, nie blankietowa penalizacja',
    paragraphs: [
      'Składający apel popiera cel projektu w zakresie ochrony pacjentów przed świadczeniodawcami działającymi w złej wierze. Wskazuje natomiast, że obecny tekst UD207: nie zapewnia jawnej, niezależnej procedury oceny merytorycznej z gradacją dowodów; nie spełnia konstytucyjnych standardów określoności prawa i proporcjonalności; nie wypełnia strukturalnej luki w systemie publicznej opieki zdrowotnej (NFZ); nie został poprzedzony rzetelnymi konsultacjami z reprezentatywnymi organizacjami pacjentów wszystkich grup chorobowych; powiela mechanizmy represyjne, których strukturalne wady wykazała już praktyka orzecznicza Sądu Najwyższego; ustawia Polskę poza głównym nurtem regulacyjnym UE i WHO.',
      'Pakiet obywatelski przedstawia konkretną alternatywę — naprawę, nie porzucenie celu — opartą na zasadach: (1) klauzula świadomej zgody pacjenta jako ustawowe wyłączenie z sankcji dla świadczeń wspomagających, które nie stwarzają bezpośredniego zagrożenia i nie zastępują leczenia o udokumentowanej skuteczności; (2) wyłączenie świadczeń realizowanych w legalnych trybach (badanie kliniczne, eksperyment leczniczy za zgodą komisji bioetycznej i pacjenta, off-label, import docelowy, legalne stosowanie w UE) — dla onkologii szybkie i odbiurokratyzowane; (3) jawna, niezależna procedura ekspercka z gradacją dowodów i ujawnianiem konfliktów interesów jako warunek proporcjonalności uprawnień; (4) realna, merytoryczna kontrola decyzji RPP przez niezależny sąd powszechny (model UOKiK — Sąd Ochrony Konkurencji i Konsumentów) z automatycznym wstrzymaniem skutków po złożeniu odwołania; (5) zakaz publikacji nieprawomocnych decyzji; (6) ciągłość opieki jako obowiązek każdej decyzji wyłączającej świadczeniodawcę; (7) mądra regulacja przez kwalifikacje i rejestr zamiast penalizacji; (8) wyłączenie „dezinformacji” z natychmiastowych sankcji i przeniesienie jej do osobnego trybu/rejestru.',
      'Kierunek pozytywny: zamiast represji państwo powinno wspierać niezależne badania i standaryzację jakości — na wzór rozwiązań w innych państwach Unii Europejskiej. Podnosi to bezpieczeństwo pacjentów, rozwija polską naukę i odciąża przeciążony system publiczny, zamiast spychać świadczenia do szarej strefy.',
      'Hierarchia oczekiwań wobec procesu legislacyjnego: (1) Sejm (Komisja Zdrowia, pełna izba) — wprowadzenie poprawek sanacyjnych zgodnych z powyższymi zasadami; (2) Senat — równoległy tor sanacyjny lub odrzucenie projektu w razie braku poprawek; (3) Prezydent RP — odmowa podpisu (art. 122 ust. 5) lub skierowanie do TK (art. 122 ust. 3) wyłącznie w razie uchwalenia ustawy bez poprawek; (4) Rzecznik Praw Obywatelskich — równolegle, ocena konstytucyjności i ewentualne wystąpienie do TK (art. 191 ust. 1 pkt 1 Konstytucji RP).',
      'Pełna dokumentacja konstytucyjna, prawna i empiryczna dostępna jest publicznie na stronie pacjentmaprawo.pl (sekcje: „Czego się domagamy”, „Na tle Europy”, „Memorandum prawne UD207”).',
    ],
  },
]

export const FULL_PETITION_TEXT: string = [
  PETITION_TITLE,
  '',
  ...PETITION_SECTIONS.flatMap((s) => [s.heading, ...s.paragraphs, '']),
  'Pełna dokumentacja: pacjentmaprawo.pl',
]
  .join('\n')
  .trim()
